### ISSUE TITLE
Extract the footnotes

### ISSUE THREAD

**Issue by proclamo** [ChrisTorng/gd2md-html#2]
We need to extract the [footnotes](https://developers.google.com/apps-script/reference/document/footnote) of a document.

The contents of the footnote should be converted also to Markdown ((footnotes on Markdown)[https://www.markdownguide.org/extended-syntax/#footnotes])

**Comment by ChrisTorng** [comment]
It's already done, reference to wiki [Text element conversion features](https://github.com/evbacher/gd2md-html/wiki#text-element-conversion-features). Closing this.
