### ISSUE TITLE
Extract the images

### ISSUE THREAD

**Issue by proclamo** [ChrisTorng/gd2md-html#3]
Apps Script API for Google Docs allows to [read the embedded images](https://developers.google.com/apps-script/reference/document/inline-image).

The [getBlob()](https://developers.google.com/apps-script/reference/document/inline-image#getBlob()) method allows extracting the image data to convert it to Markdown base64.

**Comment by ChrisTorng** [comment]
Markdown is not primary goal for this repo. HTML will be necessary. If Markdown implement is easy after HTML, then it may be done then.

**Comment by ChrisTorng** [comment]
Embedded image finished in https://github.com/ChrisTorng/gd2md-html/commit/cbcc07521609ae7bfb9c38f2bc448e9dd4788e78. I'll do more tests to check whether this is finished.

**Comment by ChrisTorng** [comment]
Hitting "Array length 50000001 exceeds supported capacity limit." error. Seems JavaScript's string object can't handle this long embedded image string. Needs to find out ways to overcome this restriction.

**Comment by ChrisTorng** [comment]
call flushBuffer every time, then another error "ScriptError: Exceeded maximum execution time" raised.

**Comment by ChrisTorng** [comment]
This issue is been solved by https://github.com/ChrisTorng/gd2md-html/commit/071bdf7bfbf1012ed466bd581c0e68d8529b67d8.
